---
name: Test-Slow
version: 0.02
author:
  - 'Tomáš Znamenáček <zoul@fleuron.cz>'
abstract: Skip test that are too slow to run frequently
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/zoul/Test-Slow
requires:
  Test::More: 0
  perl: v5.8.0
configure_requires:
  Module::Build: 0.35
provides:
  Test::Slow:
    file: lib/Test/Slow.pm
    version: 0.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
